<?php

declare(strict_types=1);

/*
 * SpotifyWebAPILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace SpotifyWebAPILib\Models\Builders;

use Core\Utils\CoreHelper;
use SpotifyWebAPILib\Models\AlbumRestrictionObject;

/**
 * Builder for model AlbumRestrictionObject
 *
 * @see AlbumRestrictionObject
 */
class AlbumRestrictionObjectBuilder
{
    /**
     * @var AlbumRestrictionObject
     */
    private $instance;

    private function __construct(AlbumRestrictionObject $instance)
    {
        $this->instance = $instance;
    }

    /**
     * Initializes a new album restriction object Builder object.
     */
    public static function init(): self
    {
        return new self(new AlbumRestrictionObject());
    }

    /**
     * Sets reason field.
     */
    public function reason(?string $value): self
    {
        $this->instance->setReason($value);
        return $this;
    }

    /**
     * Initializes a new album restriction object object.
     */
    public function build(): AlbumRestrictionObject
    {
        return CoreHelper::clone($this->instance);
    }
}
