<?php

declare(strict_types=1);

/*
 * SpotifyWebAPILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace SpotifyWebAPILib\Models\Builders;

use Core\Utils\CoreHelper;
use SpotifyWebAPILib\Models\AlbumBase;
use SpotifyWebAPILib\Models\AlbumRestrictionObject;
use SpotifyWebAPILib\Models\ExternalUrlObject;

/**
 * Builder for model AlbumBase
 *
 * @see AlbumBase
 */
class AlbumBaseBuilder
{
    /**
     * @var AlbumBase
     */
    private $instance;

    private function __construct(AlbumBase $instance)
    {
        $this->instance = $instance;
    }

    /**
     * Initializes a new album base Builder object.
     */
    public static function init(
        string $albumType,
        int $totalTracks,
        array $availableMarkets,
        ExternalUrlObject $externalUrls,
        string $href,
        string $id,
        array $images,
        string $name,
        string $releaseDate,
        string $releaseDatePrecision,
        string $type,
        string $uri
    ): self {
        return new self(new AlbumBase(
            $albumType,
            $totalTracks,
            $availableMarkets,
            $externalUrls,
            $href,
            $id,
            $images,
            $name,
            $releaseDate,
            $releaseDatePrecision,
            $type,
            $uri
        ));
    }

    /**
     * Sets restrictions field.
     */
    public function restrictions(?AlbumRestrictionObject $value): self
    {
        $this->instance->setRestrictions($value);
        return $this;
    }

    /**
     * Initializes a new album base object.
     */
    public function build(): AlbumBase
    {
        return CoreHelper::clone($this->instance);
    }
}
