<?php

declare(strict_types=1);

/*
 * SpotifyWebAPILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace SpotifyWebAPILib\Models\Builders;

use Core\Utils\CoreHelper;
use SpotifyWebAPILib\Models\AlbumObject;
use SpotifyWebAPILib\Models\AlbumRestrictionObject;
use SpotifyWebAPILib\Models\ExternalIdObject;
use SpotifyWebAPILib\Models\ExternalUrlObject;
use SpotifyWebAPILib\Models\PagingSimplifiedTrackObject;

/**
 * Builder for model AlbumObject
 *
 * @see AlbumObject
 */
class AlbumObjectBuilder
{
    /**
     * @var AlbumObject
     */
    private $instance;

    private function __construct(AlbumObject $instance)
    {
        $this->instance = $instance;
    }

    /**
     * Initializes a new album object Builder object.
     */
    public static function init(
        string $albumType,
        int $totalTracks,
        array $availableMarkets,
        ExternalUrlObject $externalUrls,
        string $href,
        string $id,
        array $images,
        string $name,
        string $releaseDate,
        string $releaseDatePrecision,
        string $type,
        string $uri,
        array $artists,
        PagingSimplifiedTrackObject $tracks,
        array $copyrights,
        ExternalIdObject $externalIds,
        array $genres,
        string $label,
        int $popularity
    ): self {
        return new self(new AlbumObject(
            $albumType,
            $totalTracks,
            $availableMarkets,
            $externalUrls,
            $href,
            $id,
            $images,
            $name,
            $releaseDate,
            $releaseDatePrecision,
            $type,
            $uri,
            $artists,
            $tracks,
            $copyrights,
            $externalIds,
            $genres,
            $label,
            $popularity
        ));
    }

    /**
     * Sets restrictions field.
     */
    public function restrictions(?AlbumRestrictionObject $value): self
    {
        $this->instance->setRestrictions($value);
        return $this;
    }

    /**
     * Initializes a new album object object.
     */
    public function build(): AlbumObject
    {
        return CoreHelper::clone($this->instance);
    }
}
