<?php

declare(strict_types=1);

/*
 * SpotifyWebAPILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace SpotifyWebAPILib\Models\Builders;

use Core\Utils\CoreHelper;
use SpotifyWebAPILib\Models\AudiobookBase;
use SpotifyWebAPILib\Models\ExternalUrlObject;

/**
 * Builder for model AudiobookBase
 *
 * @see AudiobookBase
 */
class AudiobookBaseBuilder
{
    /**
     * @var AudiobookBase
     */
    private $instance;

    private function __construct(AudiobookBase $instance)
    {
        $this->instance = $instance;
    }

    /**
     * Initializes a new audiobook base Builder object.
     */
    public static function init(
        array $authors,
        array $availableMarkets,
        array $copyrights,
        string $description,
        string $htmlDescription,
        bool $explicit,
        ExternalUrlObject $externalUrls,
        string $href,
        string $id,
        array $images,
        array $languages,
        string $mediaType,
        string $name,
        array $narrators,
        string $publisher,
        string $type,
        string $uri,
        int $totalChapters
    ): self {
        return new self(new AudiobookBase(
            $authors,
            $availableMarkets,
            $copyrights,
            $description,
            $htmlDescription,
            $explicit,
            $externalUrls,
            $href,
            $id,
            $images,
            $languages,
            $mediaType,
            $name,
            $narrators,
            $publisher,
            $type,
            $uri,
            $totalChapters
        ));
    }

    /**
     * Sets edition field.
     */
    public function edition(?string $value): self
    {
        $this->instance->setEdition($value);
        return $this;
    }

    /**
     * Initializes a new audiobook base object.
     */
    public function build(): AudiobookBase
    {
        return CoreHelper::clone($this->instance);
    }
}
