<?php

declare(strict_types=1);

/*
 * SpotifyWebAPILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace SpotifyWebAPILib\Models\Builders;

use Core\Utils\CoreHelper;
use SpotifyWebAPILib\Models\AuthorObject;

/**
 * Builder for model AuthorObject
 *
 * @see AuthorObject
 */
class AuthorObjectBuilder
{
    /**
     * @var AuthorObject
     */
    private $instance;

    private function __construct(AuthorObject $instance)
    {
        $this->instance = $instance;
    }

    /**
     * Initializes a new author object Builder object.
     */
    public static function init(): self
    {
        return new self(new AuthorObject());
    }

    /**
     * Sets name field.
     */
    public function name(?string $value): self
    {
        $this->instance->setName($value);
        return $this;
    }

    /**
     * Initializes a new author object object.
     */
    public function build(): AuthorObject
    {
        return CoreHelper::clone($this->instance);
    }
}
