<?php

declare(strict_types=1);

/*
 * SpotifyWebAPILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace SpotifyWebAPILib\Models\Builders;

use Core\Utils\CoreHelper;
use SpotifyWebAPILib\Models\CategoryObject;

/**
 * Builder for model CategoryObject
 *
 * @see CategoryObject
 */
class CategoryObjectBuilder
{
    /**
     * @var CategoryObject
     */
    private $instance;

    private function __construct(CategoryObject $instance)
    {
        $this->instance = $instance;
    }

    /**
     * Initializes a new category object Builder object.
     */
    public static function init(string $href, array $icons, string $id, string $name): self
    {
        return new self(new CategoryObject($href, $icons, $id, $name));
    }

    /**
     * Initializes a new category object object.
     */
    public function build(): CategoryObject
    {
        return CoreHelper::clone($this->instance);
    }
}
