<?php

declare(strict_types=1);

/*
 * SpotifyWebAPILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace SpotifyWebAPILib\Models\Builders;

use Core\Utils\CoreHelper;
use SpotifyWebAPILib\Models\CursorPagedArtists;
use SpotifyWebAPILib\Models\CursorPagingSimplifiedArtistObject;

/**
 * Builder for model CursorPagedArtists
 *
 * @see CursorPagedArtists
 */
class CursorPagedArtistsBuilder
{
    /**
     * @var CursorPagedArtists
     */
    private $instance;

    private function __construct(CursorPagedArtists $instance)
    {
        $this->instance = $instance;
    }

    /**
     * Initializes a new cursor paged artists Builder object.
     */
    public static function init(CursorPagingSimplifiedArtistObject $artists): self
    {
        return new self(new CursorPagedArtists($artists));
    }

    /**
     * Initializes a new cursor paged artists object.
     */
    public function build(): CursorPagedArtists
    {
        return CoreHelper::clone($this->instance);
    }
}
