<?php

declare(strict_types=1);

/*
 * SpotifyWebAPILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace SpotifyWebAPILib\Models\Builders;

use Core\Utils\CoreHelper;
use SpotifyWebAPILib\Models\DeviceObject;

/**
 * Builder for model DeviceObject
 *
 * @see DeviceObject
 */
class DeviceObjectBuilder
{
    /**
     * @var DeviceObject
     */
    private $instance;

    private function __construct(DeviceObject $instance)
    {
        $this->instance = $instance;
    }

    /**
     * Initializes a new device object Builder object.
     */
    public static function init(): self
    {
        return new self(new DeviceObject());
    }

    /**
     * Sets id field.
     */
    public function id(?string $value): self
    {
        $this->instance->setId($value);
        return $this;
    }

    /**
     * Unsets id field.
     */
    public function unsetId(): self
    {
        $this->instance->unsetId();
        return $this;
    }

    /**
     * Sets is active field.
     */
    public function isActive(?bool $value): self
    {
        $this->instance->setIsActive($value);
        return $this;
    }

    /**
     * Sets is private session field.
     */
    public function isPrivateSession(?bool $value): self
    {
        $this->instance->setIsPrivateSession($value);
        return $this;
    }

    /**
     * Sets is restricted field.
     */
    public function isRestricted(?bool $value): self
    {
        $this->instance->setIsRestricted($value);
        return $this;
    }

    /**
     * Sets name field.
     */
    public function name(?string $value): self
    {
        $this->instance->setName($value);
        return $this;
    }

    /**
     * Sets type field.
     */
    public function type(?string $value): self
    {
        $this->instance->setType($value);
        return $this;
    }

    /**
     * Sets volume percent field.
     */
    public function volumePercent(?int $value): self
    {
        $this->instance->setVolumePercent($value);
        return $this;
    }

    /**
     * Unsets volume percent field.
     */
    public function unsetVolumePercent(): self
    {
        $this->instance->unsetVolumePercent();
        return $this;
    }

    /**
     * Sets supports volume field.
     */
    public function supportsVolume(?bool $value): self
    {
        $this->instance->setSupportsVolume($value);
        return $this;
    }

    /**
     * Initializes a new device object object.
     */
    public function build(): DeviceObject
    {
        return CoreHelper::clone($this->instance);
    }
}
