<?php

declare(strict_types=1);

/*
 * SpotifyWebAPILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace SpotifyWebAPILib\Models\Builders;

use Core\Utils\CoreHelper;
use SpotifyWebAPILib\Models\EpisodeRestrictionObject;

/**
 * Builder for model EpisodeRestrictionObject
 *
 * @see EpisodeRestrictionObject
 */
class EpisodeRestrictionObjectBuilder
{
    /**
     * @var EpisodeRestrictionObject
     */
    private $instance;

    private function __construct(EpisodeRestrictionObject $instance)
    {
        $this->instance = $instance;
    }

    /**
     * Initializes a new episode restriction object Builder object.
     */
    public static function init(): self
    {
        return new self(new EpisodeRestrictionObject());
    }

    /**
     * Sets reason field.
     */
    public function reason(?string $value): self
    {
        $this->instance->setReason($value);
        return $this;
    }

    /**
     * Initializes a new episode restriction object object.
     */
    public function build(): EpisodeRestrictionObject
    {
        return CoreHelper::clone($this->instance);
    }
}
