<?php

declare(strict_types=1);

/*
 * SpotifyWebAPILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace SpotifyWebAPILib\Models\Builders;

use Core\Utils\CoreHelper;
use SpotifyWebAPILib\Models\EpisodeObject;
use SpotifyWebAPILib\Models\EpisodeRestrictionObject;
use SpotifyWebAPILib\Models\ExternalUrlObject;
use SpotifyWebAPILib\Models\ResumePointObject;
use SpotifyWebAPILib\Models\ShowBase;

/**
 * Builder for model EpisodeObject
 *
 * @see EpisodeObject
 */
class EpisodeObjectBuilder
{
    /**
     * @var EpisodeObject
     */
    private $instance;

    private function __construct(EpisodeObject $instance)
    {
        $this->instance = $instance;
    }

    /**
     * Initializes a new episode object Builder object.
     */
    public static function init(
        string $description,
        string $htmlDescription,
        int $durationMs,
        bool $explicit,
        ExternalUrlObject $externalUrls,
        string $href,
        string $id,
        array $images,
        bool $isExternallyHosted,
        bool $isPlayable,
        array $languages,
        string $name,
        string $releaseDate,
        string $releaseDatePrecision,
        string $type,
        string $uri,
        ShowBase $show
    ): self {
        return new self(new EpisodeObject(
            $description,
            $htmlDescription,
            $durationMs,
            $explicit,
            $externalUrls,
            $href,
            $id,
            $images,
            $isExternallyHosted,
            $isPlayable,
            $languages,
            $name,
            $releaseDate,
            $releaseDatePrecision,
            $type,
            $uri,
            $show
        ));
    }

    /**
     * Sets audio preview url field.
     */
    public function audioPreviewUrl(?string $value): self
    {
        $this->instance->setAudioPreviewUrl($value);
        return $this;
    }

    /**
     * Sets language field.
     */
    public function language(?string $value): self
    {
        $this->instance->setLanguage($value);
        return $this;
    }

    /**
     * Sets resume point field.
     */
    public function resumePoint(?ResumePointObject $value): self
    {
        $this->instance->setResumePoint($value);
        return $this;
    }

    /**
     * Sets restrictions field.
     */
    public function restrictions(?EpisodeRestrictionObject $value): self
    {
        $this->instance->setRestrictions($value);
        return $this;
    }

    /**
     * Initializes a new episode object object.
     */
    public function build(): EpisodeObject
    {
        return CoreHelper::clone($this->instance);
    }
}
