<?php

declare(strict_types=1);

/*
 * SpotifyWebAPILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace SpotifyWebAPILib\Models\Builders;

use Core\Utils\CoreHelper;
use SpotifyWebAPILib\Models\ExternalUrlObject;

/**
 * Builder for model ExternalUrlObject
 *
 * @see ExternalUrlObject
 */
class ExternalUrlObjectBuilder
{
    /**
     * @var ExternalUrlObject
     */
    private $instance;

    private function __construct(ExternalUrlObject $instance)
    {
        $this->instance = $instance;
    }

    /**
     * Initializes a new external url object Builder object.
     */
    public static function init(): self
    {
        return new self(new ExternalUrlObject());
    }

    /**
     * Sets spotify field.
     */
    public function spotify(?string $value): self
    {
        $this->instance->setSpotify($value);
        return $this;
    }

    /**
     * Initializes a new external url object object.
     */
    public function build(): ExternalUrlObject
    {
        return CoreHelper::clone($this->instance);
    }
}
