<?php

declare(strict_types=1);

/*
 * SpotifyWebAPILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace SpotifyWebAPILib\Models\Builders;

use Core\Utils\CoreHelper;
use SpotifyWebAPILib\Models\ExternalIdObject;

/**
 * Builder for model ExternalIdObject
 *
 * @see ExternalIdObject
 */
class ExternalIdObjectBuilder
{
    /**
     * @var ExternalIdObject
     */
    private $instance;

    private function __construct(ExternalIdObject $instance)
    {
        $this->instance = $instance;
    }

    /**
     * Initializes a new external id object Builder object.
     */
    public static function init(): self
    {
        return new self(new ExternalIdObject());
    }

    /**
     * Sets isrc field.
     */
    public function isrc(?string $value): self
    {
        $this->instance->setIsrc($value);
        return $this;
    }

    /**
     * Sets ean field.
     */
    public function ean(?string $value): self
    {
        $this->instance->setEan($value);
        return $this;
    }

    /**
     * Sets upc field.
     */
    public function upc(?string $value): self
    {
        $this->instance->setUpc($value);
        return $this;
    }

    /**
     * Initializes a new external id object object.
     */
    public function build(): ExternalIdObject
    {
        return CoreHelper::clone($this->instance);
    }
}
