<?php

declare(strict_types=1);

/*
 * SpotifyWebAPILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace SpotifyWebAPILib\Models\Builders;

use Core\Utils\CoreHelper;
use SpotifyWebAPILib\Models\ExternalUrlObject;
use SpotifyWebAPILib\Models\LinkedTrackObject;

/**
 * Builder for model LinkedTrackObject
 *
 * @see LinkedTrackObject
 */
class LinkedTrackObjectBuilder
{
    /**
     * @var LinkedTrackObject
     */
    private $instance;

    private function __construct(LinkedTrackObject $instance)
    {
        $this->instance = $instance;
    }

    /**
     * Initializes a new linked track object Builder object.
     */
    public static function init(): self
    {
        return new self(new LinkedTrackObject());
    }

    /**
     * Sets external urls field.
     */
    public function externalUrls(?ExternalUrlObject $value): self
    {
        $this->instance->setExternalUrls($value);
        return $this;
    }

    /**
     * Sets href field.
     */
    public function href(?string $value): self
    {
        $this->instance->setHref($value);
        return $this;
    }

    /**
     * Sets id field.
     */
    public function id(?string $value): self
    {
        $this->instance->setId($value);
        return $this;
    }

    /**
     * Sets type field.
     */
    public function type(?string $value): self
    {
        $this->instance->setType($value);
        return $this;
    }

    /**
     * Sets uri field.
     */
    public function uri(?string $value): self
    {
        $this->instance->setUri($value);
        return $this;
    }

    /**
     * Initializes a new linked track object object.
     */
    public function build(): LinkedTrackObject
    {
        return CoreHelper::clone($this->instance);
    }
}
