<?php

declare(strict_types=1);

/*
 * SpotifyWebAPILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace SpotifyWebAPILib\Models\Builders;

use Core\Utils\CoreHelper;
use SpotifyWebAPILib\Models\ManyGenres;

/**
 * Builder for model ManyGenres
 *
 * @see ManyGenres
 */
class ManyGenresBuilder
{
    /**
     * @var ManyGenres
     */
    private $instance;

    private function __construct(ManyGenres $instance)
    {
        $this->instance = $instance;
    }

    /**
     * Initializes a new many genres Builder object.
     */
    public static function init(array $genres): self
    {
        return new self(new ManyGenres($genres));
    }

    /**
     * Initializes a new many genres object.
     */
    public function build(): ManyGenres
    {
        return CoreHelper::clone($this->instance);
    }
}
