<?php

declare(strict_types=1);

/*
 * SpotifyWebAPILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace SpotifyWebAPILib\Models\Builders;

use Core\Utils\CoreHelper;
use SpotifyWebAPILib\Models\ManyDevices;

/**
 * Builder for model ManyDevices
 *
 * @see ManyDevices
 */
class ManyDevicesBuilder
{
    /**
     * @var ManyDevices
     */
    private $instance;

    private function __construct(ManyDevices $instance)
    {
        $this->instance = $instance;
    }

    /**
     * Initializes a new many devices Builder object.
     */
    public static function init(array $devices): self
    {
        return new self(new ManyDevices($devices));
    }

    /**
     * Initializes a new many devices object.
     */
    public function build(): ManyDevices
    {
        return CoreHelper::clone($this->instance);
    }
}
