<?php

declare(strict_types=1);

/*
 * SpotifyWebAPILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace SpotifyWebAPILib\Models\Builders;

use Core\Utils\CoreHelper;
use SpotifyWebAPILib\Models\ManyChapters;

/**
 * Builder for model ManyChapters
 *
 * @see ManyChapters
 */
class ManyChaptersBuilder
{
    /**
     * @var ManyChapters
     */
    private $instance;

    private function __construct(ManyChapters $instance)
    {
        $this->instance = $instance;
    }

    /**
     * Initializes a new many chapters Builder object.
     */
    public static function init(array $chapters): self
    {
        return new self(new ManyChapters($chapters));
    }

    /**
     * Initializes a new many chapters object.
     */
    public function build(): ManyChapters
    {
        return CoreHelper::clone($this->instance);
    }
}
