<?php

declare(strict_types=1);

/*
 * SpotifyWebAPILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace SpotifyWebAPILib\Models\Builders;

use Core\Utils\CoreHelper;
use SpotifyWebAPILib\Models\ManySimplifiedShows;

/**
 * Builder for model ManySimplifiedShows
 *
 * @see ManySimplifiedShows
 */
class ManySimplifiedShowsBuilder
{
    /**
     * @var ManySimplifiedShows
     */
    private $instance;

    private function __construct(ManySimplifiedShows $instance)
    {
        $this->instance = $instance;
    }

    /**
     * Initializes a new many simplified shows Builder object.
     */
    public static function init(array $shows): self
    {
        return new self(new ManySimplifiedShows($shows));
    }

    /**
     * Initializes a new many simplified shows object.
     */
    public function build(): ManySimplifiedShows
    {
        return CoreHelper::clone($this->instance);
    }
}
