<?php

declare(strict_types=1);

/*
 * SpotifyWebAPILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace SpotifyWebAPILib\Models\Builders;

use Core\Utils\CoreHelper;
use SpotifyWebAPILib\Models\ManyArtists;

/**
 * Builder for model ManyArtists
 *
 * @see ManyArtists
 */
class ManyArtistsBuilder
{
    /**
     * @var ManyArtists
     */
    private $instance;

    private function __construct(ManyArtists $instance)
    {
        $this->instance = $instance;
    }

    /**
     * Initializes a new many artists Builder object.
     */
    public static function init(array $artists): self
    {
        return new self(new ManyArtists($artists));
    }

    /**
     * Initializes a new many artists object.
     */
    public function build(): ManyArtists
    {
        return CoreHelper::clone($this->instance);
    }
}
