<?php

declare(strict_types=1);

/*
 * SpotifyWebAPILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace SpotifyWebAPILib\Models\Builders;

use Core\Utils\CoreHelper;
use SpotifyWebAPILib\Models\MeAlbumsRequest;

/**
 * Builder for model MeAlbumsRequest
 *
 * @see MeAlbumsRequest
 */
class MeAlbumsRequestBuilder
{
    /**
     * @var MeAlbumsRequest
     */
    private $instance;

    private function __construct(MeAlbumsRequest $instance)
    {
        $this->instance = $instance;
    }

    /**
     * Initializes a new me albums request Builder object.
     */
    public static function init(): self
    {
        return new self(new MeAlbumsRequest());
    }

    /**
     * Sets ids field.
     */
    public function ids(?array $value): self
    {
        $this->instance->setIds($value);
        return $this;
    }

    /**
     * Initializes a new me albums request object.
     */
    public function build(): MeAlbumsRequest
    {
        return CoreHelper::clone($this->instance);
    }
}
