<?php

declare(strict_types=1);

/*
 * SpotifyWebAPILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace SpotifyWebAPILib\Models\Builders;

use Core\Utils\CoreHelper;
use SpotifyWebAPILib\Models\MeFollowingRequest;

/**
 * Builder for model MeFollowingRequest
 *
 * @see MeFollowingRequest
 */
class MeFollowingRequestBuilder
{
    /**
     * @var MeFollowingRequest
     */
    private $instance;

    private function __construct(MeFollowingRequest $instance)
    {
        $this->instance = $instance;
    }

    /**
     * Initializes a new me following request Builder object.
     */
    public static function init(array $ids): self
    {
        return new self(new MeFollowingRequest($ids));
    }

    /**
     * Initializes a new me following request object.
     */
    public function build(): MeFollowingRequest
    {
        return CoreHelper::clone($this->instance);
    }
}
