<?php

declare(strict_types=1);

/*
 * SpotifyWebAPILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace SpotifyWebAPILib\Models\Builders;

use Core\Utils\CoreHelper;
use SpotifyWebAPILib\Models\MePlayerPlayRequest;

/**
 * Builder for model MePlayerPlayRequest
 *
 * @see MePlayerPlayRequest
 */
class MePlayerPlayRequestBuilder
{
    /**
     * @var MePlayerPlayRequest
     */
    private $instance;

    private function __construct(MePlayerPlayRequest $instance)
    {
        $this->instance = $instance;
    }

    /**
     * Initializes a new me player play request Builder object.
     */
    public static function init(): self
    {
        return new self(new MePlayerPlayRequest());
    }

    /**
     * Sets context uri field.
     */
    public function contextUri(?string $value): self
    {
        $this->instance->setContextUri($value);
        return $this;
    }

    /**
     * Sets uris field.
     */
    public function uris(?array $value): self
    {
        $this->instance->setUris($value);
        return $this;
    }

    /**
     * Sets offset field.
     */
    public function offset(?array $value): self
    {
        $this->instance->setOffset($value);
        return $this;
    }

    /**
     * Sets position ms field.
     */
    public function positionMs(?int $value): self
    {
        $this->instance->setPositionMs($value);
        return $this;
    }

    /**
     * Initializes a new me player play request object.
     */
    public function build(): MePlayerPlayRequest
    {
        return CoreHelper::clone($this->instance);
    }
}
