<?php

declare(strict_types=1);

/*
 * SpotifyWebAPILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace SpotifyWebAPILib\Models\Builders;

use Core\Utils\CoreHelper;
use SpotifyWebAPILib\Models\MeShowsRequest;

/**
 * Builder for model MeShowsRequest
 *
 * @see MeShowsRequest
 */
class MeShowsRequestBuilder
{
    /**
     * @var MeShowsRequest
     */
    private $instance;

    private function __construct(MeShowsRequest $instance)
    {
        $this->instance = $instance;
    }

    /**
     * Initializes a new me shows request Builder object.
     */
    public static function init(): self
    {
        return new self(new MeShowsRequest());
    }

    /**
     * Sets ids field.
     */
    public function ids(?array $value): self
    {
        $this->instance->setIds($value);
        return $this;
    }

    /**
     * Initializes a new me shows request object.
     */
    public function build(): MeShowsRequest
    {
        return CoreHelper::clone($this->instance);
    }
}
