<?php

declare(strict_types=1);

/*
 * SpotifyWebAPILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace SpotifyWebAPILib\Models\Builders;

use Core\Utils\CoreHelper;
use SpotifyWebAPILib\Models\MeTracksRequest;

/**
 * Builder for model MeTracksRequest
 *
 * @see MeTracksRequest
 */
class MeTracksRequestBuilder
{
    /**
     * @var MeTracksRequest
     */
    private $instance;

    private function __construct(MeTracksRequest $instance)
    {
        $this->instance = $instance;
    }

    /**
     * Initializes a new me tracks request Builder object.
     */
    public static function init(array $ids): self
    {
        return new self(new MeTracksRequest($ids));
    }

    /**
     * Initializes a new me tracks request object.
     */
    public function build(): MeTracksRequest
    {
        return CoreHelper::clone($this->instance);
    }
}
