<?php

declare(strict_types=1);

/*
 * SpotifyWebAPILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace SpotifyWebAPILib\Models\Builders;

use Core\Utils\CoreHelper;
use SpotifyWebAPILib\Models\MeTracksRequest1;

/**
 * Builder for model MeTracksRequest1
 *
 * @see MeTracksRequest1
 */
class MeTracksRequest1Builder
{
    /**
     * @var MeTracksRequest1
     */
    private $instance;

    private function __construct(MeTracksRequest1 $instance)
    {
        $this->instance = $instance;
    }

    /**
     * Initializes a new me tracks request 1 Builder object.
     */
    public static function init(): self
    {
        return new self(new MeTracksRequest1());
    }

    /**
     * Sets ids field.
     */
    public function ids(?array $value): self
    {
        $this->instance->setIds($value);
        return $this;
    }

    /**
     * Initializes a new me tracks request 1 object.
     */
    public function build(): MeTracksRequest1
    {
        return CoreHelper::clone($this->instance);
    }
}
