<?php

declare(strict_types=1);

/*
 * SpotifyWebAPILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace SpotifyWebAPILib\Models\Builders;

use Core\Utils\CoreHelper;
use SpotifyWebAPILib\Models\NarratorObject;

/**
 * Builder for model NarratorObject
 *
 * @see NarratorObject
 */
class NarratorObjectBuilder
{
    /**
     * @var NarratorObject
     */
    private $instance;

    private function __construct(NarratorObject $instance)
    {
        $this->instance = $instance;
    }

    /**
     * Initializes a new narrator object Builder object.
     */
    public static function init(): self
    {
        return new self(new NarratorObject());
    }

    /**
     * Sets name field.
     */
    public function name(?string $value): self
    {
        $this->instance->setName($value);
        return $this;
    }

    /**
     * Initializes a new narrator object object.
     */
    public function build(): NarratorObject
    {
        return CoreHelper::clone($this->instance);
    }
}
