<?php

declare(strict_types=1);

/*
 * SpotifyWebAPILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace SpotifyWebAPILib\Models\Builders;

use Core\Utils\CoreHelper;
use SpotifyWebAPILib\Models\PagedAlbums;
use SpotifyWebAPILib\Models\PagingSimplifiedAlbumObject;

/**
 * Builder for model PagedAlbums
 *
 * @see PagedAlbums
 */
class PagedAlbumsBuilder
{
    /**
     * @var PagedAlbums
     */
    private $instance;

    private function __construct(PagedAlbums $instance)
    {
        $this->instance = $instance;
    }

    /**
     * Initializes a new paged albums Builder object.
     */
    public static function init(PagingSimplifiedAlbumObject $albums): self
    {
        return new self(new PagedAlbums($albums));
    }

    /**
     * Initializes a new paged albums object.
     */
    public function build(): PagedAlbums
    {
        return CoreHelper::clone($this->instance);
    }
}
