<?php

declare(strict_types=1);

/*
 * SpotifyWebAPILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace SpotifyWebAPILib\Models\Builders;

use Core\Utils\CoreHelper;
use SpotifyWebAPILib\Models\Categories;
use SpotifyWebAPILib\Models\PagedCategories;

/**
 * Builder for model PagedCategories
 *
 * @see PagedCategories
 */
class PagedCategoriesBuilder
{
    /**
     * @var PagedCategories
     */
    private $instance;

    private function __construct(PagedCategories $instance)
    {
        $this->instance = $instance;
    }

    /**
     * Initializes a new paged categories Builder object.
     */
    public static function init(Categories $categories): self
    {
        return new self(new PagedCategories($categories));
    }

    /**
     * Initializes a new paged categories object.
     */
    public function build(): PagedCategories
    {
        return CoreHelper::clone($this->instance);
    }
}
