<?php

declare(strict_types=1);

/*
 * SpotifyWebAPILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace SpotifyWebAPILib\Models\Builders;

use Core\Utils\CoreHelper;
use SpotifyWebAPILib\Models\PlaylistsTracksRequest;

/**
 * Builder for model PlaylistsTracksRequest
 *
 * @see PlaylistsTracksRequest
 */
class PlaylistsTracksRequestBuilder
{
    /**
     * @var PlaylistsTracksRequest
     */
    private $instance;

    private function __construct(PlaylistsTracksRequest $instance)
    {
        $this->instance = $instance;
    }

    /**
     * Initializes a new playlists tracks request Builder object.
     */
    public static function init(): self
    {
        return new self(new PlaylistsTracksRequest());
    }

    /**
     * Sets uris field.
     */
    public function uris(?array $value): self
    {
        $this->instance->setUris($value);
        return $this;
    }

    /**
     * Sets position field.
     */
    public function position(?int $value): self
    {
        $this->instance->setPosition($value);
        return $this;
    }

    /**
     * Initializes a new playlists tracks request object.
     */
    public function build(): PlaylistsTracksRequest
    {
        return CoreHelper::clone($this->instance);
    }
}
