<?php

declare(strict_types=1);

/*
 * SpotifyWebAPILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace SpotifyWebAPILib\Models\Builders;

use Core\Utils\CoreHelper;
use SpotifyWebAPILib\Models\PlaylistsTracksRequest1;

/**
 * Builder for model PlaylistsTracksRequest1
 *
 * @see PlaylistsTracksRequest1
 */
class PlaylistsTracksRequest1Builder
{
    /**
     * @var PlaylistsTracksRequest1
     */
    private $instance;

    private function __construct(PlaylistsTracksRequest1 $instance)
    {
        $this->instance = $instance;
    }

    /**
     * Initializes a new playlists tracks request 1 Builder object.
     */
    public static function init(): self
    {
        return new self(new PlaylistsTracksRequest1());
    }

    /**
     * Sets uris field.
     */
    public function uris(?array $value): self
    {
        $this->instance->setUris($value);
        return $this;
    }

    /**
     * Sets range start field.
     */
    public function rangeStart(?int $value): self
    {
        $this->instance->setRangeStart($value);
        return $this;
    }

    /**
     * Sets insert before field.
     */
    public function insertBefore(?int $value): self
    {
        $this->instance->setInsertBefore($value);
        return $this;
    }

    /**
     * Sets range length field.
     */
    public function rangeLength(?int $value): self
    {
        $this->instance->setRangeLength($value);
        return $this;
    }

    /**
     * Sets snapshot id field.
     */
    public function snapshotId(?string $value): self
    {
        $this->instance->setSnapshotId($value);
        return $this;
    }

    /**
     * Initializes a new playlists tracks request 1 object.
     */
    public function build(): PlaylistsTracksRequest1
    {
        return CoreHelper::clone($this->instance);
    }
}
