<?php

declare(strict_types=1);

/*
 * SpotifyWebAPILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace SpotifyWebAPILib\Models\Builders;

use Core\Utils\CoreHelper;
use SpotifyWebAPILib\Models\PlaylistsRequest;

/**
 * Builder for model PlaylistsRequest
 *
 * @see PlaylistsRequest
 */
class PlaylistsRequestBuilder
{
    /**
     * @var PlaylistsRequest
     */
    private $instance;

    private function __construct(PlaylistsRequest $instance)
    {
        $this->instance = $instance;
    }

    /**
     * Initializes a new playlists request Builder object.
     */
    public static function init(): self
    {
        return new self(new PlaylistsRequest());
    }

    /**
     * Sets name field.
     */
    public function name(?string $value): self
    {
        $this->instance->setName($value);
        return $this;
    }

    /**
     * Sets public field.
     */
    public function public(?bool $value): self
    {
        $this->instance->setPublic($value);
        return $this;
    }

    /**
     * Sets collaborative field.
     */
    public function collaborative(?bool $value): self
    {
        $this->instance->setCollaborative($value);
        return $this;
    }

    /**
     * Sets description field.
     */
    public function description(?string $value): self
    {
        $this->instance->setDescription($value);
        return $this;
    }

    /**
     * Initializes a new playlists request object.
     */
    public function build(): PlaylistsRequest
    {
        return CoreHelper::clone($this->instance);
    }
}
