<?php

declare(strict_types=1);

/*
 * SpotifyWebAPILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace SpotifyWebAPILib\Models\Builders;

use Core\Utils\CoreHelper;
use SpotifyWebAPILib\Models\ResumePointObject;

/**
 * Builder for model ResumePointObject
 *
 * @see ResumePointObject
 */
class ResumePointObjectBuilder
{
    /**
     * @var ResumePointObject
     */
    private $instance;

    private function __construct(ResumePointObject $instance)
    {
        $this->instance = $instance;
    }

    /**
     * Initializes a new resume point object Builder object.
     */
    public static function init(): self
    {
        return new self(new ResumePointObject());
    }

    /**
     * Sets fully played field.
     */
    public function fullyPlayed(?bool $value): self
    {
        $this->instance->setFullyPlayed($value);
        return $this;
    }

    /**
     * Sets resume position ms field.
     */
    public function resumePositionMs(?int $value): self
    {
        $this->instance->setResumePositionMs($value);
        return $this;
    }

    /**
     * Initializes a new resume point object object.
     */
    public function build(): ResumePointObject
    {
        return CoreHelper::clone($this->instance);
    }
}
