<?php

declare(strict_types=1);

/*
 * SpotifyWebAPILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace SpotifyWebAPILib\Models\Builders;

use Core\Utils\CoreHelper;
use SpotifyWebAPILib\Models\EpisodeObject;
use SpotifyWebAPILib\Models\SavedEpisodeObject;

/**
 * Builder for model SavedEpisodeObject
 *
 * @see SavedEpisodeObject
 */
class SavedEpisodeObjectBuilder
{
    /**
     * @var SavedEpisodeObject
     */
    private $instance;

    private function __construct(SavedEpisodeObject $instance)
    {
        $this->instance = $instance;
    }

    /**
     * Initializes a new saved episode object Builder object.
     */
    public static function init(): self
    {
        return new self(new SavedEpisodeObject());
    }

    /**
     * Sets added at field.
     */
    public function addedAt(?\DateTime $value): self
    {
        $this->instance->setAddedAt($value);
        return $this;
    }

    /**
     * Sets episode field.
     */
    public function episode(?EpisodeObject $value): self
    {
        $this->instance->setEpisode($value);
        return $this;
    }

    /**
     * Initializes a new saved episode object object.
     */
    public function build(): SavedEpisodeObject
    {
        return CoreHelper::clone($this->instance);
    }
}
