<?php

declare(strict_types=1);

/*
 * SpotifyWebAPILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace SpotifyWebAPILib\Models\Builders;

use Core\Utils\CoreHelper;
use SpotifyWebAPILib\Models\SavedShowObject;
use SpotifyWebAPILib\Models\ShowBase;

/**
 * Builder for model SavedShowObject
 *
 * @see SavedShowObject
 */
class SavedShowObjectBuilder
{
    /**
     * @var SavedShowObject
     */
    private $instance;

    private function __construct(SavedShowObject $instance)
    {
        $this->instance = $instance;
    }

    /**
     * Initializes a new saved show object Builder object.
     */
    public static function init(): self
    {
        return new self(new SavedShowObject());
    }

    /**
     * Sets added at field.
     */
    public function addedAt(?\DateTime $value): self
    {
        $this->instance->setAddedAt($value);
        return $this;
    }

    /**
     * Sets show field.
     */
    public function show(?ShowBase $value): self
    {
        $this->instance->setShow($value);
        return $this;
    }

    /**
     * Initializes a new saved show object object.
     */
    public function build(): SavedShowObject
    {
        return CoreHelper::clone($this->instance);
    }
}
