<?php

declare(strict_types=1);

/*
 * SpotifyWebAPILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace SpotifyWebAPILib\Models\Builders;

use Core\Utils\CoreHelper;
use SpotifyWebAPILib\Models\SegmentObject;

/**
 * Builder for model SegmentObject
 *
 * @see SegmentObject
 */
class SegmentObjectBuilder
{
    /**
     * @var SegmentObject
     */
    private $instance;

    private function __construct(SegmentObject $instance)
    {
        $this->instance = $instance;
    }

    /**
     * Initializes a new segment object Builder object.
     */
    public static function init(): self
    {
        return new self(new SegmentObject());
    }

    /**
     * Sets start field.
     */
    public function start(?float $value): self
    {
        $this->instance->setStart($value);
        return $this;
    }

    /**
     * Sets duration field.
     */
    public function duration(?float $value): self
    {
        $this->instance->setDuration($value);
        return $this;
    }

    /**
     * Sets confidence field.
     */
    public function confidence(?float $value): self
    {
        $this->instance->setConfidence($value);
        return $this;
    }

    /**
     * Sets loudness start field.
     */
    public function loudnessStart(?float $value): self
    {
        $this->instance->setLoudnessStart($value);
        return $this;
    }

    /**
     * Sets loudness max field.
     */
    public function loudnessMax(?float $value): self
    {
        $this->instance->setLoudnessMax($value);
        return $this;
    }

    /**
     * Sets loudness max time field.
     */
    public function loudnessMaxTime(?float $value): self
    {
        $this->instance->setLoudnessMaxTime($value);
        return $this;
    }

    /**
     * Sets loudness end field.
     */
    public function loudnessEnd(?float $value): self
    {
        $this->instance->setLoudnessEnd($value);
        return $this;
    }

    /**
     * Sets pitches field.
     */
    public function pitches(?array $value): self
    {
        $this->instance->setPitches($value);
        return $this;
    }

    /**
     * Sets timbre field.
     */
    public function timbre(?array $value): self
    {
        $this->instance->setTimbre($value);
        return $this;
    }

    /**
     * Initializes a new segment object object.
     */
    public function build(): SegmentObject
    {
        return CoreHelper::clone($this->instance);
    }
}
