<?php

declare(strict_types=1);

/*
 * SpotifyWebAPILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace SpotifyWebAPILib\Models\Builders;

use Core\Utils\CoreHelper;
use SpotifyWebAPILib\Models\AlbumRestrictionObject;
use SpotifyWebAPILib\Models\ExternalUrlObject;
use SpotifyWebAPILib\Models\SimplifiedAlbumObject;

/**
 * Builder for model SimplifiedAlbumObject
 *
 * @see SimplifiedAlbumObject
 */
class SimplifiedAlbumObjectBuilder
{
    /**
     * @var SimplifiedAlbumObject
     */
    private $instance;

    private function __construct(SimplifiedAlbumObject $instance)
    {
        $this->instance = $instance;
    }

    /**
     * Initializes a new simplified album object Builder object.
     */
    public static function init(
        string $albumType,
        int $totalTracks,
        array $availableMarkets,
        ExternalUrlObject $externalUrls,
        string $href,
        string $id,
        array $images,
        string $name,
        string $releaseDate,
        string $releaseDatePrecision,
        string $type,
        string $uri,
        array $artists
    ): self {
        return new self(new SimplifiedAlbumObject(
            $albumType,
            $totalTracks,
            $availableMarkets,
            $externalUrls,
            $href,
            $id,
            $images,
            $name,
            $releaseDate,
            $releaseDatePrecision,
            $type,
            $uri,
            $artists
        ));
    }

    /**
     * Sets restrictions field.
     */
    public function restrictions(?AlbumRestrictionObject $value): self
    {
        $this->instance->setRestrictions($value);
        return $this;
    }

    /**
     * Initializes a new simplified album object object.
     */
    public function build(): SimplifiedAlbumObject
    {
        return CoreHelper::clone($this->instance);
    }
}
