<?php

declare(strict_types=1);

/*
 * SpotifyWebAPILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace SpotifyWebAPILib\Models\Builders;

use Core\Utils\CoreHelper;
use SpotifyWebAPILib\Models\Track1;

/**
 * Builder for model Track1
 *
 * @see Track1
 */
class Track1Builder
{
    /**
     * @var Track1
     */
    private $instance;

    private function __construct(Track1 $instance)
    {
        $this->instance = $instance;
    }

    /**
     * Initializes a new track 1 Builder object.
     */
    public static function init(): self
    {
        return new self(new Track1());
    }

    /**
     * Sets uri field.
     */
    public function uri(?string $value): self
    {
        $this->instance->setUri($value);
        return $this;
    }

    /**
     * Initializes a new track 1 object.
     */
    public function build(): Track1
    {
        return CoreHelper::clone($this->instance);
    }
}
