<?php

declare(strict_types=1);

/*
 * SpotifyWebAPILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace SpotifyWebAPILib\Models\Builders;

use Core\Utils\CoreHelper;
use SpotifyWebAPILib\Models\UsersPlaylistsRequest;

/**
 * Builder for model UsersPlaylistsRequest
 *
 * @see UsersPlaylistsRequest
 */
class UsersPlaylistsRequestBuilder
{
    /**
     * @var UsersPlaylistsRequest
     */
    private $instance;

    private function __construct(UsersPlaylistsRequest $instance)
    {
        $this->instance = $instance;
    }

    /**
     * Initializes a new users playlists request Builder object.
     */
    public static function init(string $name): self
    {
        return new self(new UsersPlaylistsRequest($name));
    }

    /**
     * Sets public field.
     */
    public function public(?bool $value): self
    {
        $this->instance->setPublic($value);
        return $this;
    }

    /**
     * Sets collaborative field.
     */
    public function collaborative(?bool $value): self
    {
        $this->instance->setCollaborative($value);
        return $this;
    }

    /**
     * Sets description field.
     */
    public function description(?string $value): self
    {
        $this->instance->setDescription($value);
        return $this;
    }

    /**
     * Initializes a new users playlists request object.
     */
    public function build(): UsersPlaylistsRequest
    {
        return CoreHelper::clone($this->instance);
    }
}
