<?php

declare(strict_types=1);

/*
 * SpotifyWebAPILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace SpotifyWebAPILib\Models;

use Core\Utils\CoreHelper;
use Exception;
use stdClass;

/**
 * This field describes the relationship between the artist and the album.
 */
class AlbumGroupEnum
{
    public const ALBUM = 'album';

    public const SINGLE = 'single';

    public const COMPILATION = 'compilation';

    public const APPEARS_ON = 'appears_on';

    private const _ALL_VALUES = [self::ALBUM, self::SINGLE, self::COMPILATION, self::APPEARS_ON];

    /**
     * Ensures that all the given values are present in this Enum.
     *
     * @param array|stdClass|null|string $value Value or a list/map of values to be checked
     *
     * @return array|null|string Input value(s), if all are a part of this Enum
     *
     * @throws Exception Throws exception if any given value is not in this Enum
     */
    public static function checkValue($value)
    {
        $value = json_decode(json_encode($value), true); // converts stdClass into array
        if (CoreHelper::checkValueOrValuesInList($value, self::_ALL_VALUES)) {
            return $value;
        }
        throw new Exception("$value is invalid for AlbumGroupEnum.");
    }
}
