<?php

declare(strict_types=1);

/*
 * SpotifyWebAPILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace SpotifyWebAPILib\Models;

use stdClass;

class AlbumRestrictionObject implements \JsonSerializable
{
    /**
     * @var string|null
     */
    private $reason;

    /**
     * Returns Reason.
     * The reason for the restriction. Albums may be restricted if the content is not available in a given
     * market, to the user's subscription type, or when the user's account is set to not play explicit
     * content.
     * Additional reasons may be added in the future.
     */
    public function getReason(): ?string
    {
        return $this->reason;
    }

    /**
     * Sets Reason.
     * The reason for the restriction. Albums may be restricted if the content is not available in a given
     * market, to the user's subscription type, or when the user's account is set to not play explicit
     * content.
     * Additional reasons may be added in the future.
     *
     * @maps reason
     * @factory \SpotifyWebAPILib\Models\ReasonEnum::checkValue
     */
    public function setReason(?string $reason): void
    {
        $this->reason = $reason;
    }

    /**
     * Encode this object to JSON
     *
     * @param bool $asArrayWhenEmpty Whether to serialize this model as an array whenever no fields
     *        are set. (default: false)
     *
     * @return array|stdClass
     */
    #[\ReturnTypeWillChange] // @phan-suppress-current-line PhanUndeclaredClassAttribute for (php < 8.1)
    public function jsonSerialize(bool $asArrayWhenEmpty = false)
    {
        $json = [];
        if (isset($this->reason)) {
            $json['reason'] = ReasonEnum::checkValue($this->reason);
        }

        return (!$asArrayWhenEmpty && empty($json)) ? new stdClass() : $json;
    }
}
