<?php

declare(strict_types=1);

/*
 * SpotifyWebAPILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace SpotifyWebAPILib\Models;

use stdClass;

class ArtistObject implements \JsonSerializable
{
    /**
     * @var ExternalUrlObject|null
     */
    private $externalUrls;

    /**
     * @var FollowersObject|null
     */
    private $followers;

    /**
     * @var string[]|null
     */
    private $genres;

    /**
     * @var string|null
     */
    private $href;

    /**
     * @var string|null
     */
    private $id;

    /**
     * @var ImageObject[]|null
     */
    private $images;

    /**
     * @var string|null
     */
    private $name;

    /**
     * @var int|null
     */
    private $popularity;

    /**
     * @var string|null
     */
    private $type;

    /**
     * @var string|null
     */
    private $uri;

    /**
     * Returns External Urls.
     * Known external URLs for this artist.
     */
    public function getExternalUrls(): ?ExternalUrlObject
    {
        return $this->externalUrls;
    }

    /**
     * Sets External Urls.
     * Known external URLs for this artist.
     *
     * @maps external_urls
     */
    public function setExternalUrls(?ExternalUrlObject $externalUrls): void
    {
        $this->externalUrls = $externalUrls;
    }

    /**
     * Returns Followers.
     * Information about the followers of the artist.
     */
    public function getFollowers(): ?FollowersObject
    {
        return $this->followers;
    }

    /**
     * Sets Followers.
     * Information about the followers of the artist.
     *
     * @maps followers
     */
    public function setFollowers(?FollowersObject $followers): void
    {
        $this->followers = $followers;
    }

    /**
     * Returns Genres.
     * A list of the genres the artist is associated with. If not yet classified, the array is empty.
     *
     * @return string[]|null
     */
    public function getGenres(): ?array
    {
        return $this->genres;
    }

    /**
     * Sets Genres.
     * A list of the genres the artist is associated with. If not yet classified, the array is empty.
     *
     * @maps genres
     *
     * @param string[]|null $genres
     */
    public function setGenres(?array $genres): void
    {
        $this->genres = $genres;
    }

    /**
     * Returns Href.
     * A link to the Web API endpoint providing full details of the artist.
     */
    public function getHref(): ?string
    {
        return $this->href;
    }

    /**
     * Sets Href.
     * A link to the Web API endpoint providing full details of the artist.
     *
     * @maps href
     */
    public function setHref(?string $href): void
    {
        $this->href = $href;
    }

    /**
     * Returns Id.
     * The [Spotify ID](/documentation/web-api/concepts/spotify-uris-ids) for the artist.
     */
    public function getId(): ?string
    {
        return $this->id;
    }

    /**
     * Sets Id.
     * The [Spotify ID](/documentation/web-api/concepts/spotify-uris-ids) for the artist.
     *
     * @maps id
     */
    public function setId(?string $id): void
    {
        $this->id = $id;
    }

    /**
     * Returns Images.
     * Images of the artist in various sizes, widest first.
     *
     * @return ImageObject[]|null
     */
    public function getImages(): ?array
    {
        return $this->images;
    }

    /**
     * Sets Images.
     * Images of the artist in various sizes, widest first.
     *
     * @maps images
     *
     * @param ImageObject[]|null $images
     */
    public function setImages(?array $images): void
    {
        $this->images = $images;
    }

    /**
     * Returns Name.
     * The name of the artist.
     */
    public function getName(): ?string
    {
        return $this->name;
    }

    /**
     * Sets Name.
     * The name of the artist.
     *
     * @maps name
     */
    public function setName(?string $name): void
    {
        $this->name = $name;
    }

    /**
     * Returns Popularity.
     * The popularity of the artist. The value will be between 0 and 100, with 100 being the most popular.
     * The artist's popularity is calculated from the popularity of all the artist's tracks.
     */
    public function getPopularity(): ?int
    {
        return $this->popularity;
    }

    /**
     * Sets Popularity.
     * The popularity of the artist. The value will be between 0 and 100, with 100 being the most popular.
     * The artist's popularity is calculated from the popularity of all the artist's tracks.
     *
     * @maps popularity
     */
    public function setPopularity(?int $popularity): void
    {
        $this->popularity = $popularity;
    }

    /**
     * Returns Type.
     * The object type.
     */
    public function getType(): ?string
    {
        return $this->type;
    }

    /**
     * Sets Type.
     * The object type.
     *
     * @maps type
     * @factory \SpotifyWebAPILib\Models\TypeEnum::checkValue
     */
    public function setType(?string $type): void
    {
        $this->type = $type;
    }

    /**
     * Returns Uri.
     * The [Spotify URI](/documentation/web-api/concepts/spotify-uris-ids) for the artist.
     */
    public function getUri(): ?string
    {
        return $this->uri;
    }

    /**
     * Sets Uri.
     * The [Spotify URI](/documentation/web-api/concepts/spotify-uris-ids) for the artist.
     *
     * @maps uri
     */
    public function setUri(?string $uri): void
    {
        $this->uri = $uri;
    }

    /**
     * Encode this object to JSON
     *
     * @param bool $asArrayWhenEmpty Whether to serialize this model as an array whenever no fields
     *        are set. (default: false)
     *
     * @return array|stdClass
     */
    #[\ReturnTypeWillChange] // @phan-suppress-current-line PhanUndeclaredClassAttribute for (php < 8.1)
    public function jsonSerialize(bool $asArrayWhenEmpty = false)
    {
        $json = [];
        if (isset($this->externalUrls)) {
            $json['external_urls'] = $this->externalUrls;
        }
        if (isset($this->followers)) {
            $json['followers']     = $this->followers;
        }
        if (isset($this->genres)) {
            $json['genres']        = $this->genres;
        }
        if (isset($this->href)) {
            $json['href']          = $this->href;
        }
        if (isset($this->id)) {
            $json['id']            = $this->id;
        }
        if (isset($this->images)) {
            $json['images']        = $this->images;
        }
        if (isset($this->name)) {
            $json['name']          = $this->name;
        }
        if (isset($this->popularity)) {
            $json['popularity']    = $this->popularity;
        }
        if (isset($this->type)) {
            $json['type']          = TypeEnum::checkValue($this->type);
        }
        if (isset($this->uri)) {
            $json['uri']           = $this->uri;
        }

        return (!$asArrayWhenEmpty && empty($json)) ? new stdClass() : $json;
    }
}
