<?php

declare(strict_types=1);

/*
 * SpotifyWebAPILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace SpotifyWebAPILib\Models;

use stdClass;

class CopyrightObject implements \JsonSerializable
{
    /**
     * @var string|null
     */
    private $text;

    /**
     * @var string|null
     */
    private $type;

    /**
     * Returns Text.
     * The copyright text for this content.
     */
    public function getText(): ?string
    {
        return $this->text;
    }

    /**
     * Sets Text.
     * The copyright text for this content.
     *
     * @maps text
     */
    public function setText(?string $text): void
    {
        $this->text = $text;
    }

    /**
     * Returns Type.
     * The type of copyright: `C` = the copyright, `P` = the sound recording (performance) copyright.
     */
    public function getType(): ?string
    {
        return $this->type;
    }

    /**
     * Sets Type.
     * The type of copyright: `C` = the copyright, `P` = the sound recording (performance) copyright.
     *
     * @maps type
     */
    public function setType(?string $type): void
    {
        $this->type = $type;
    }

    /**
     * Encode this object to JSON
     *
     * @param bool $asArrayWhenEmpty Whether to serialize this model as an array whenever no fields
     *        are set. (default: false)
     *
     * @return array|stdClass
     */
    #[\ReturnTypeWillChange] // @phan-suppress-current-line PhanUndeclaredClassAttribute for (php < 8.1)
    public function jsonSerialize(bool $asArrayWhenEmpty = false)
    {
        $json = [];
        if (isset($this->text)) {
            $json['text'] = $this->text;
        }
        if (isset($this->type)) {
            $json['type'] = $this->type;
        }

        return (!$asArrayWhenEmpty && empty($json)) ? new stdClass() : $json;
    }
}
