<?php

declare(strict_types=1);

/*
 * SpotifyWebAPILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace SpotifyWebAPILib\Models;

use stdClass;

class CursorPagedArtists implements \JsonSerializable
{
    /**
     * @var CursorPagingSimplifiedArtistObject
     */
    private $artists;

    /**
     * @param CursorPagingSimplifiedArtistObject $artists
     */
    public function __construct(CursorPagingSimplifiedArtistObject $artists)
    {
        $this->artists = $artists;
    }

    /**
     * Returns Artists.
     */
    public function getArtists(): CursorPagingSimplifiedArtistObject
    {
        return $this->artists;
    }

    /**
     * Sets Artists.
     *
     * @required
     * @maps artists
     */
    public function setArtists(CursorPagingSimplifiedArtistObject $artists): void
    {
        $this->artists = $artists;
    }

    /**
     * Encode this object to JSON
     *
     * @param bool $asArrayWhenEmpty Whether to serialize this model as an array whenever no fields
     *        are set. (default: false)
     *
     * @return array|stdClass
     */
    #[\ReturnTypeWillChange] // @phan-suppress-current-line PhanUndeclaredClassAttribute for (php < 8.1)
    public function jsonSerialize(bool $asArrayWhenEmpty = false)
    {
        $json = [];
        $json['artists'] = $this->artists;

        return (!$asArrayWhenEmpty && empty($json)) ? new stdClass() : $json;
    }
}
