<?php

declare(strict_types=1);

/*
 * SpotifyWebAPILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace SpotifyWebAPILib\Models;

use stdClass;

class ExternalUrlObject implements \JsonSerializable
{
    /**
     * @var string|null
     */
    private $spotify;

    /**
     * Returns Spotify.
     * The [Spotify URL](/documentation/web-api/concepts/spotify-uris-ids) for the object.
     */
    public function getSpotify(): ?string
    {
        return $this->spotify;
    }

    /**
     * Sets Spotify.
     * The [Spotify URL](/documentation/web-api/concepts/spotify-uris-ids) for the object.
     *
     * @maps spotify
     */
    public function setSpotify(?string $spotify): void
    {
        $this->spotify = $spotify;
    }

    /**
     * Encode this object to JSON
     *
     * @param bool $asArrayWhenEmpty Whether to serialize this model as an array whenever no fields
     *        are set. (default: false)
     *
     * @return array|stdClass
     */
    #[\ReturnTypeWillChange] // @phan-suppress-current-line PhanUndeclaredClassAttribute for (php < 8.1)
    public function jsonSerialize(bool $asArrayWhenEmpty = false)
    {
        $json = [];
        if (isset($this->spotify)) {
            $json['spotify'] = $this->spotify;
        }

        return (!$asArrayWhenEmpty && empty($json)) ? new stdClass() : $json;
    }
}
