<?php

declare(strict_types=1);

/*
 * SpotifyWebAPILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace SpotifyWebAPILib\Models;

use stdClass;

class FollowersObject implements \JsonSerializable
{
    /**
     * @var array
     */
    private $href = [];

    /**
     * @var int|null
     */
    private $total;

    /**
     * Returns Href.
     * This will always be set to null, as the Web API does not support it at the moment.
     */
    public function getHref(): ?string
    {
        if (count($this->href) == 0) {
            return null;
        }
        return $this->href['value'];
    }

    /**
     * Sets Href.
     * This will always be set to null, as the Web API does not support it at the moment.
     *
     * @maps href
     */
    public function setHref(?string $href): void
    {
        $this->href['value'] = $href;
    }

    /**
     * Unsets Href.
     * This will always be set to null, as the Web API does not support it at the moment.
     */
    public function unsetHref(): void
    {
        $this->href = [];
    }

    /**
     * Returns Total.
     * The total number of followers.
     */
    public function getTotal(): ?int
    {
        return $this->total;
    }

    /**
     * Sets Total.
     * The total number of followers.
     *
     * @maps total
     */
    public function setTotal(?int $total): void
    {
        $this->total = $total;
    }

    /**
     * Encode this object to JSON
     *
     * @param bool $asArrayWhenEmpty Whether to serialize this model as an array whenever no fields
     *        are set. (default: false)
     *
     * @return array|stdClass
     */
    #[\ReturnTypeWillChange] // @phan-suppress-current-line PhanUndeclaredClassAttribute for (php < 8.1)
    public function jsonSerialize(bool $asArrayWhenEmpty = false)
    {
        $json = [];
        if (!empty($this->href)) {
            $json['href']  = $this->href['value'];
        }
        if (isset($this->total)) {
            $json['total'] = $this->total;
        }

        return (!$asArrayWhenEmpty && empty($json)) ? new stdClass() : $json;
    }
}
