<?php

declare(strict_types=1);

/*
 * SpotifyWebAPILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace SpotifyWebAPILib\Models;

use stdClass;

class ManyGenres implements \JsonSerializable
{
    /**
     * @var string[]
     */
    private $genres;

    /**
     * @param string[] $genres
     */
    public function __construct(array $genres)
    {
        $this->genres = $genres;
    }

    /**
     * Returns Genres.
     *
     * @return string[]
     */
    public function getGenres(): array
    {
        return $this->genres;
    }

    /**
     * Sets Genres.
     *
     * @required
     * @maps genres
     *
     * @param string[] $genres
     */
    public function setGenres(array $genres): void
    {
        $this->genres = $genres;
    }

    /**
     * Encode this object to JSON
     *
     * @param bool $asArrayWhenEmpty Whether to serialize this model as an array whenever no fields
     *        are set. (default: false)
     *
     * @return array|stdClass
     */
    #[\ReturnTypeWillChange] // @phan-suppress-current-line PhanUndeclaredClassAttribute for (php < 8.1)
    public function jsonSerialize(bool $asArrayWhenEmpty = false)
    {
        $json = [];
        $json['genres'] = $this->genres;

        return (!$asArrayWhenEmpty && empty($json)) ? new stdClass() : $json;
    }
}
