<?php

declare(strict_types=1);

/*
 * SpotifyWebAPILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace SpotifyWebAPILib\Models;

use stdClass;

class ManyEpisodes implements \JsonSerializable
{
    /**
     * @var EpisodeObject[]
     */
    private $episodes;

    /**
     * @param EpisodeObject[] $episodes
     */
    public function __construct(array $episodes)
    {
        $this->episodes = $episodes;
    }

    /**
     * Returns Episodes.
     *
     * @return EpisodeObject[]
     */
    public function getEpisodes(): array
    {
        return $this->episodes;
    }

    /**
     * Sets Episodes.
     *
     * @required
     * @maps episodes
     *
     * @param EpisodeObject[] $episodes
     */
    public function setEpisodes(array $episodes): void
    {
        $this->episodes = $episodes;
    }

    /**
     * Encode this object to JSON
     *
     * @param bool $asArrayWhenEmpty Whether to serialize this model as an array whenever no fields
     *        are set. (default: false)
     *
     * @return array|stdClass
     */
    #[\ReturnTypeWillChange] // @phan-suppress-current-line PhanUndeclaredClassAttribute for (php < 8.1)
    public function jsonSerialize(bool $asArrayWhenEmpty = false)
    {
        $json = [];
        $json['episodes'] = $this->episodes;

        return (!$asArrayWhenEmpty && empty($json)) ? new stdClass() : $json;
    }
}
