<?php

declare(strict_types=1);

/*
 * SpotifyWebAPILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace SpotifyWebAPILib\Models;

use stdClass;

class ManyAlbums implements \JsonSerializable
{
    /**
     * @var AlbumObject[]
     */
    private $albums;

    /**
     * @param AlbumObject[] $albums
     */
    public function __construct(array $albums)
    {
        $this->albums = $albums;
    }

    /**
     * Returns Albums.
     *
     * @return AlbumObject[]
     */
    public function getAlbums(): array
    {
        return $this->albums;
    }

    /**
     * Sets Albums.
     *
     * @required
     * @maps albums
     *
     * @param AlbumObject[] $albums
     */
    public function setAlbums(array $albums): void
    {
        $this->albums = $albums;
    }

    /**
     * Encode this object to JSON
     *
     * @param bool $asArrayWhenEmpty Whether to serialize this model as an array whenever no fields
     *        are set. (default: false)
     *
     * @return array|stdClass
     */
    #[\ReturnTypeWillChange] // @phan-suppress-current-line PhanUndeclaredClassAttribute for (php < 8.1)
    public function jsonSerialize(bool $asArrayWhenEmpty = false)
    {
        $json = [];
        $json['albums'] = $this->albums;

        return (!$asArrayWhenEmpty && empty($json)) ? new stdClass() : $json;
    }
}
