<?php

declare(strict_types=1);

/*
 * SpotifyWebAPILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace SpotifyWebAPILib\Models;

use stdClass;

class Markets implements \JsonSerializable
{
    /**
     * @var string[]|null
     */
    private $markets;

    /**
     * Returns Markets.
     *
     * @return string[]|null
     */
    public function getMarkets(): ?array
    {
        return $this->markets;
    }

    /**
     * Sets Markets.
     *
     * @maps markets
     *
     * @param string[]|null $markets
     */
    public function setMarkets(?array $markets): void
    {
        $this->markets = $markets;
    }

    /**
     * Encode this object to JSON
     *
     * @param bool $asArrayWhenEmpty Whether to serialize this model as an array whenever no fields
     *        are set. (default: false)
     *
     * @return array|stdClass
     */
    #[\ReturnTypeWillChange] // @phan-suppress-current-line PhanUndeclaredClassAttribute for (php < 8.1)
    public function jsonSerialize(bool $asArrayWhenEmpty = false)
    {
        $json = [];
        if (isset($this->markets)) {
            $json['markets'] = $this->markets;
        }

        return (!$asArrayWhenEmpty && empty($json)) ? new stdClass() : $json;
    }
}
