<?php

declare(strict_types=1);

/*
 * SpotifyWebAPILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace SpotifyWebAPILib\Models;

use Core\Utils\CoreHelper;
use Exception;
use stdClass;

/**
 * Indicates the modality (major or minor) of a section, the type of scale from which its melodic
 * content is derived. This field will contain a 0 for "minor", a 1 for "major", or a -1 for no result.
 * Note that the major key (e.g. C major) could more likely be confused with the minor key at 3
 * semitones lower (e.g. A minor) as both keys carry the same pitches.
 */
class ModeEnum
{
    public const ENUM_MINUS1 = -1;

    public const ENUM_0 = 0;

    public const ENUM_1 = 1;

    private const _ALL_VALUES = [self::ENUM_MINUS1, self::ENUM_0, self::ENUM_1];

    /**
     * Ensures that all the given values are present in this Enum.
     *
     * @param array|stdClass|null|int $value Value or a list/map of values to be checked
     *
     * @return array|null|int Input value(s), if all are a part of this Enum
     *
     * @throws Exception Throws exception if any given value is not in this Enum
     */
    public static function checkValue($value)
    {
        $value = json_decode(json_encode($value), true); // converts stdClass into array
        if (CoreHelper::checkValueOrValuesInList($value, self::_ALL_VALUES)) {
            return $value;
        }
        throw new Exception("$value is invalid for ModeEnum.");
    }
}
