<?php

declare(strict_types=1);

/*
 * SpotifyWebAPILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace SpotifyWebAPILib\Models;

use stdClass;

class PagingFeaturedPlaylistObject implements \JsonSerializable
{
    /**
     * @var string|null
     */
    private $message;

    /**
     * @var PagingPlaylistObject|null
     */
    private $playlists;

    /**
     * Returns Message.
     * The localized message of a playlist.
     */
    public function getMessage(): ?string
    {
        return $this->message;
    }

    /**
     * Sets Message.
     * The localized message of a playlist.
     *
     * @maps message
     */
    public function setMessage(?string $message): void
    {
        $this->message = $message;
    }

    /**
     * Returns Playlists.
     */
    public function getPlaylists(): ?PagingPlaylistObject
    {
        return $this->playlists;
    }

    /**
     * Sets Playlists.
     *
     * @maps playlists
     */
    public function setPlaylists(?PagingPlaylistObject $playlists): void
    {
        $this->playlists = $playlists;
    }

    /**
     * Encode this object to JSON
     *
     * @param bool $asArrayWhenEmpty Whether to serialize this model as an array whenever no fields
     *        are set. (default: false)
     *
     * @return array|stdClass
     */
    #[\ReturnTypeWillChange] // @phan-suppress-current-line PhanUndeclaredClassAttribute for (php < 8.1)
    public function jsonSerialize(bool $asArrayWhenEmpty = false)
    {
        $json = [];
        if (isset($this->message)) {
            $json['message']   = $this->message;
        }
        if (isset($this->playlists)) {
            $json['playlists'] = $this->playlists;
        }

        return (!$asArrayWhenEmpty && empty($json)) ? new stdClass() : $json;
    }
}
