<?php

declare(strict_types=1);

/*
 * SpotifyWebAPILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace SpotifyWebAPILib\Models;

use SpotifyWebAPILib\Utils\DateTimeHelper;
use stdClass;

class PlaylistTrackObject implements \JsonSerializable
{
    /**
     * @var \DateTime|null
     */
    private $addedAt;

    /**
     * @var PlaylistUserObject|null
     */
    private $addedBy;

    /**
     * @var bool|null
     */
    private $isLocal;

    /**
     * @var array|null
     */
    private $track;

    /**
     * Returns Added At.
     * The date and time the track or episode was added. _**Note**: some very old playlists may return
     * `null` in this field._
     */
    public function getAddedAt(): ?\DateTime
    {
        return $this->addedAt;
    }

    /**
     * Sets Added At.
     * The date and time the track or episode was added. _**Note**: some very old playlists may return
     * `null` in this field._
     *
     * @maps added_at
     * @factory \SpotifyWebAPILib\Utils\DateTimeHelper::fromRfc3339DateTime
     */
    public function setAddedAt(?\DateTime $addedAt): void
    {
        $this->addedAt = $addedAt;
    }

    /**
     * Returns Added By.
     * The Spotify user who added the track or episode. _**Note**: some very old playlists may return
     * `null` in this field._
     */
    public function getAddedBy(): ?PlaylistUserObject
    {
        return $this->addedBy;
    }

    /**
     * Sets Added By.
     * The Spotify user who added the track or episode. _**Note**: some very old playlists may return
     * `null` in this field._
     *
     * @maps added_by
     */
    public function setAddedBy(?PlaylistUserObject $addedBy): void
    {
        $this->addedBy = $addedBy;
    }

    /**
     * Returns Is Local.
     * Whether this track or episode is a [local file](/documentation/web-api/concepts/playlists/#local-
     * files) or not.
     */
    public function getIsLocal(): ?bool
    {
        return $this->isLocal;
    }

    /**
     * Sets Is Local.
     * Whether this track or episode is a [local file](/documentation/web-api/concepts/playlists/#local-
     * files) or not.
     *
     * @maps is_local
     */
    public function setIsLocal(?bool $isLocal): void
    {
        $this->isLocal = $isLocal;
    }

    /**
     * Returns Track.
     * Information about the track or episode.
     */
    public function getTrack(): ?array
    {
        return $this->track;
    }

    /**
     * Sets Track.
     * Information about the track or episode.
     *
     * @maps track
     */
    public function setTrack(?array $track): void
    {
        $this->track = $track;
    }

    /**
     * Encode this object to JSON
     *
     * @param bool $asArrayWhenEmpty Whether to serialize this model as an array whenever no fields
     *        are set. (default: false)
     *
     * @return array|stdClass
     */
    #[\ReturnTypeWillChange] // @phan-suppress-current-line PhanUndeclaredClassAttribute for (php < 8.1)
    public function jsonSerialize(bool $asArrayWhenEmpty = false)
    {
        $json = [];
        if (isset($this->addedAt)) {
            $json['added_at'] = DateTimeHelper::toRfc3339DateTime($this->addedAt);
        }
        if (isset($this->addedBy)) {
            $json['added_by'] = $this->addedBy;
        }
        if (isset($this->isLocal)) {
            $json['is_local'] = $this->isLocal;
        }
        if (isset($this->track)) {
            $json['track']    = $this->track;
        }

        return (!$asArrayWhenEmpty && empty($json)) ? new stdClass() : $json;
    }
}
