<?php

declare(strict_types=1);

/*
 * SpotifyWebAPILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace SpotifyWebAPILib\Models;

use Core\Utils\CoreHelper;
use Exception;
use stdClass;

/**
 * The reason for the restriction. Albums may be restricted if the content is not available in a given
 * market, to the user's subscription type, or when the user's account is set to not play explicit
 * content.
 * Additional reasons may be added in the future.
 */
class ReasonEnum
{
    public const MARKET = 'market';

    public const PRODUCT = 'product';

    public const EXPLICIT = 'explicit';

    private const _ALL_VALUES = [self::MARKET, self::PRODUCT, self::EXPLICIT];

    /**
     * Ensures that all the given values are present in this Enum.
     *
     * @param array|stdClass|null|string $value Value or a list/map of values to be checked
     *
     * @return array|null|string Input value(s), if all are a part of this Enum
     *
     * @throws Exception Throws exception if any given value is not in this Enum
     */
    public static function checkValue($value)
    {
        $value = json_decode(json_encode($value), true); // converts stdClass into array
        if (CoreHelper::checkValueOrValuesInList($value, self::_ALL_VALUES)) {
            return $value;
        }
        throw new Exception("$value is invalid for ReasonEnum.");
    }
}
