<?php

declare(strict_types=1);

/*
 * SpotifyWebAPILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace SpotifyWebAPILib\Models;

use SpotifyWebAPILib\Utils\DateTimeHelper;
use stdClass;

class SavedEpisodeObject implements \JsonSerializable
{
    /**
     * @var \DateTime|null
     */
    private $addedAt;

    /**
     * @var EpisodeObject|null
     */
    private $episode;

    /**
     * Returns Added At.
     * The date and time the episode was saved.
     * Timestamps are returned in ISO 8601 format as Coordinated Universal Time (UTC) with a zero offset:
     * YYYY-MM-DDTHH:MM:SSZ.
     */
    public function getAddedAt(): ?\DateTime
    {
        return $this->addedAt;
    }

    /**
     * Sets Added At.
     * The date and time the episode was saved.
     * Timestamps are returned in ISO 8601 format as Coordinated Universal Time (UTC) with a zero offset:
     * YYYY-MM-DDTHH:MM:SSZ.
     *
     * @maps added_at
     * @factory \SpotifyWebAPILib\Utils\DateTimeHelper::fromRfc3339DateTime
     */
    public function setAddedAt(?\DateTime $addedAt): void
    {
        $this->addedAt = $addedAt;
    }

    /**
     * Returns Episode.
     * Information about the episode.
     */
    public function getEpisode(): ?EpisodeObject
    {
        return $this->episode;
    }

    /**
     * Sets Episode.
     * Information about the episode.
     *
     * @maps episode
     */
    public function setEpisode(?EpisodeObject $episode): void
    {
        $this->episode = $episode;
    }

    /**
     * Encode this object to JSON
     *
     * @param bool $asArrayWhenEmpty Whether to serialize this model as an array whenever no fields
     *        are set. (default: false)
     *
     * @return array|stdClass
     */
    #[\ReturnTypeWillChange] // @phan-suppress-current-line PhanUndeclaredClassAttribute for (php < 8.1)
    public function jsonSerialize(bool $asArrayWhenEmpty = false)
    {
        $json = [];
        if (isset($this->addedAt)) {
            $json['added_at'] = DateTimeHelper::toRfc3339DateTime($this->addedAt);
        }
        if (isset($this->episode)) {
            $json['episode']  = $this->episode;
        }

        return (!$asArrayWhenEmpty && empty($json)) ? new stdClass() : $json;
    }
}
