<?php

declare(strict_types=1);

/*
 * SpotifyWebAPILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace SpotifyWebAPILib\Models;

use stdClass;

class UsersPlaylistsRequest implements \JsonSerializable
{
    /**
     * @var string
     */
    private $name;

    /**
     * @var bool|null
     */
    private $public;

    /**
     * @var bool|null
     */
    private $collaborative;

    /**
     * @var string|null
     */
    private $description;

    /**
     * @param string $name
     */
    public function __construct(string $name)
    {
        $this->name = $name;
    }

    /**
     * Returns Name.
     * The name for the new playlist, for example `"Your Coolest Playlist"`. This name does not need to be
     * unique; a user may have several playlists with the same name.
     */
    public function getName(): string
    {
        return $this->name;
    }

    /**
     * Sets Name.
     * The name for the new playlist, for example `"Your Coolest Playlist"`. This name does not need to be
     * unique; a user may have several playlists with the same name.
     *
     * @required
     * @maps name
     */
    public function setName(string $name): void
    {
        $this->name = $name;
    }

    /**
     * Returns Public.
     * Defaults to `true`. If `true` the playlist will be public, if `false` it will be private. To be able
     * to create private playlists, the user must have granted the `playlist-modify-private`
     * [scope](/documentation/web-api/concepts/scopes/#list-of-scopes)
     */
    public function getPublic(): ?bool
    {
        return $this->public;
    }

    /**
     * Sets Public.
     * Defaults to `true`. If `true` the playlist will be public, if `false` it will be private. To be able
     * to create private playlists, the user must have granted the `playlist-modify-private`
     * [scope](/documentation/web-api/concepts/scopes/#list-of-scopes)
     *
     * @maps public
     */
    public function setPublic(?bool $public): void
    {
        $this->public = $public;
    }

    /**
     * Returns Collaborative.
     * Defaults to `false`. If `true` the playlist will be collaborative. _**Note**: to create a
     * collaborative playlist you must also set `public` to `false`. To create collaborative playlists you
     * must have granted `playlist-modify-private` and `playlist-modify-public` [scopes](/documentation/web-
     * api/concepts/scopes/#list-of-scopes)._
     */
    public function getCollaborative(): ?bool
    {
        return $this->collaborative;
    }

    /**
     * Sets Collaborative.
     * Defaults to `false`. If `true` the playlist will be collaborative. _**Note**: to create a
     * collaborative playlist you must also set `public` to `false`. To create collaborative playlists you
     * must have granted `playlist-modify-private` and `playlist-modify-public` [scopes](/documentation/web-
     * api/concepts/scopes/#list-of-scopes)._
     *
     * @maps collaborative
     */
    public function setCollaborative(?bool $collaborative): void
    {
        $this->collaborative = $collaborative;
    }

    /**
     * Returns Description.
     * value for playlist description as displayed in Spotify Clients and in the Web API.
     */
    public function getDescription(): ?string
    {
        return $this->description;
    }

    /**
     * Sets Description.
     * value for playlist description as displayed in Spotify Clients and in the Web API.
     *
     * @maps description
     */
    public function setDescription(?string $description): void
    {
        $this->description = $description;
    }

    /**
     * Encode this object to JSON
     *
     * @param bool $asArrayWhenEmpty Whether to serialize this model as an array whenever no fields
     *        are set. (default: false)
     *
     * @return array|stdClass
     */
    #[\ReturnTypeWillChange] // @phan-suppress-current-line PhanUndeclaredClassAttribute for (php < 8.1)
    public function jsonSerialize(bool $asArrayWhenEmpty = false)
    {
        $json = [];
        $json['name']              = $this->name;
        if (isset($this->public)) {
            $json['public']        = $this->public;
        }
        if (isset($this->collaborative)) {
            $json['collaborative'] = $this->collaborative;
        }
        if (isset($this->description)) {
            $json['description']   = $this->description;
        }

        return (!$asArrayWhenEmpty && empty($json)) ? new stdClass() : $json;
    }
}
